<a href="https://colab.research.google.com/github/TTReza/Car_Price_Prediction/blob/master/car_price_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
car = pd.read_csv('quikr_car.csv')

In [3]:
car.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [4]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

In [9]:
backup = car.copy()

In [5]:
car['Price'].unique()

array(['80,000', '4,25,000', 'Ask For Price', '3,25,000', '5,75,000',
       '1,75,000', '1,90,000', '8,30,000', '2,50,000', '1,82,000',
       '3,15,000', '4,15,000', '3,20,000', '10,00,000', '5,00,000',
       '3,50,000', '1,60,000', '3,10,000', '75,000', '1,00,000',
       '2,90,000', '95,000', '1,80,000', '3,85,000', '1,05,000',
       '6,50,000', '6,89,999', '4,48,000', '5,49,000', '5,01,000',
       '4,89,999', '2,80,000', '3,49,999', '2,84,999', '3,45,000',
       '4,99,999', '2,35,000', '2,49,999', '14,75,000', '3,95,000',
       '2,20,000', '1,70,000', '85,000', '2,00,000', '5,70,000',
       '1,10,000', '4,48,999', '18,91,111', '1,59,500', '3,44,999',
       '4,49,999', '8,65,000', '6,99,000', '3,75,000', '2,24,999',
       '12,00,000', '1,95,000', '3,51,000', '2,40,000', '90,000',
       '1,55,000', '6,00,000', '1,89,500', '2,10,000', '3,90,000',
       '1,35,000', '16,00,000', '7,01,000', '2,65,000', '5,25,000',
       '3,72,000', '6,35,000', '5,50,000', '4,85,000', '3,29,500',
       '2,51,111', '5,69,999', '69,999', '2,99,999', '3,99,999',
       '4,50,000', '2,70,000', '1,58,400', '1,79,000', '1,25,000',
       '2,99,000', '1,50,000', '2,75,000', '2,85,000', '3,40,000',
       '70,000', '2,89,999', '8,49,999', '7,49,999', '2,74,999',
       '9,84,999', '5,99,999', '2,44,999', '4,74,999', '2,45,000',
       '1,69,500', '3,70,000', '1,68,000', '1,45,000', '98,500',
       '2,09,000', '1,85,000', '9,00,000', '6,99,999', '1,99,999',
       '5,44,999', '1,99,000', '5,40,000', '49,000', '7,00,000', '55,000',
       '8,95,000', '3,55,000', '5,65,000', '3,65,000', '40,000',
       '4,00,000', '3,30,000', '5,80,000', '3,79,000', '2,19,000',
       '5,19,000', '7,30,000', '20,00,000', '21,00,000', '14,00,000',
       '3,11,000', '8,55,000', '5,35,000', '1,78,000', '3,00,000',
       '2,55,000', '5,49,999', '3,80,000', '57,000', '4,10,000',
       '2,25,000', '1,20,000', '59,000', '5,99,000', '6,75,000', '72,500',
       '6,10,000', '2,30,000', '5,20,000', '5,24,999', '4,24,999',
       '6,44,999', '5,84,999', '7,99,999', '4,44,999', '6,49,999',
       '9,44,999', '5,74,999', '3,74,999', '1,30,000', '4,01,000',
       '13,50,000', '1,74,999', '2,39,999', '99,999', '3,24,999',
       '10,74,999', '11,30,000', '1,49,000', '7,70,000', '30,000',
       '3,35,000', '3,99,000', '65,000', '1,69,999', '1,65,000',
       '5,60,000', '9,50,000', '7,15,000', '45,000', '9,40,000',
       '1,55,555', '15,00,000', '4,95,000', '8,00,000', '12,99,000',
       '5,30,000', '14,99,000', '32,000', '4,05,000', '7,60,000',
       '7,50,000', '4,19,000', '1,40,000', '15,40,000', '1,23,000',
       '4,98,000', '4,80,000', '4,88,000', '15,25,000', '5,48,900',
       '7,25,000', '99,000', '52,000', '28,00,000', '4,99,000',
       '3,81,000', '2,78,000', '6,90,000', '2,60,000', '90,001',
       '1,15,000', '15,99,000', '1,59,000', '51,999', '2,15,000',
       '35,000', '11,50,000', '2,69,000', '60,000', '4,30,000',
       '85,00,003', '4,01,919', '4,90,000', '4,24,000', '2,05,000',
       '5,49,900', '3,71,500', '4,35,000', '1,89,700', '3,89,700',
       '3,60,000', '2,95,000', '1,14,990', '10,65,000', '4,70,000',
       '48,000', '1,88,000', '4,65,000', '1,79,999', '21,90,000',
       '23,90,000', '10,75,000', '4,75,000', '10,25,000', '6,15,000',
       '19,00,000', '14,90,000', '15,10,000', '18,50,000', '7,90,000',
       '17,25,000', '12,25,000', '68,000', '9,70,000', '31,00,000',
       '8,99,000', '88,000', '53,000', '5,68,500', '71,000', '5,90,000',
       '7,95,000', '42,000', '1,89,000', '1,62,000', '35,999',
       '29,00,000', '39,999', '50,500', '5,10,000', '8,60,000',
       '5,00,001'], dtype=object)

In [6]:
car = car[car['Price'] != 'Ask For Price']

In [7]:
car['Price'] = car['Price'].str.replace(',', '').astype(int)

In [8]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 857 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        857 non-null    object
 1   company     857 non-null    object
 2   year        857 non-null    object
 3   Price       857 non-null    int64
 4   kms_driven  819 non-null    object
 5   fuel_type   816 non-null    object
dtypes: int64(1), object(5)
memory usage: 46.9+ KB

In [10]:
car['year'].unique()

array(['2007', '2006', '2014', '2012', '2013', '2016', '2015', '2010',
       '2017', '2008', '2018', '2011', '2019', '2009', '2005', '2000',
       '150k', 'TOUR', '2003', 'r 15', '2004', 'sale', '1995', 'ara)',
       '2002', 'SELL', '2001', 'tion', 'odel', '2 bs', 'arry', 'o...',
       'Zest', 'ture', 'emi', 'car', 'able', 'd...', 'SALE', 'sell',
       'd Ex', 'n...', 'e...', 'go .', 'k...', 'o c4', 'zire', 'Sumo',
       'cab', 'EV2', 'r...', 'zest'], dtype=object)

In [11]:
car = car[car['year'].str.isnumeric()]

In [12]:
car['year'] = car['year'].astype(int)

In [13]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 819 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        819 non-null    object
 1   company     819 non-null    object
 2   year        819 non-null    int64
 3   Price       819 non-null    int64
 4   kms_driven  819 non-null    object
 5   fuel_type   816 non-null    object
dtypes: int64(2), object(4)
memory usage: 44.8+ KB

In [14]:
car['kms_driven'].unique()

array(['45,000 kms', '40 kms', '28,000 kms', '36,000 kms', '41,000 kms',
       '25,000 kms', '24,530 kms', '60,000 kms', '30,000 kms',
       '32,000 kms', '48,660 kms', '4,000 kms', '16,934 kms',
       '43,000 kms', '35,550 kms', '39,522 kms', '39,000 kms',
       '55,000 kms', '72,000 kms', '15,975 kms', '70,000 kms',
       '23,452 kms', '35,522 kms', '48,508 kms', '15,487 kms',
       '82,000 kms', '20,000 kms', '68,000 kms', '38,000 kms',
       '27,000 kms', '33,000 kms', '46,000 kms', '16,000 kms',
       '47,000 kms', '35,000 kms', '30,874 kms', '15,000 kms',
       '29,685 kms', '1,30,000 kms', '19,000 kms', '54,000 kms',
       '13,000 kms', '38,200 kms', '22,000 kms', '50,000 kms',
       '13,500 kms', '3,600 kms', '45,863 kms', '60,500 kms',
       '12,500 kms', '18,000 kms', '13,349 kms', '29,000 kms',
       '44,000 kms', '42,000 kms', '14,000 kms', '49,000 kms',
       '36,200 kms', '51,000 kms', '1,04,000 kms', '33,333 kms',
       '33,600 kms', '5,600 kms', '7,500 kms', '26,000 kms', '24,330 kms',
       '65,480 kms', '2,00,000 kms', '59,000 kms', '99,000 kms',
       '2,800 kms', '21,000 kms', '11,000 kms', '66,000 kms', '3,000 kms',
       '7,000 kms', '38,500 kms', '37,200 kms', '43,200 kms',
       '24,800 kms', '45,872 kms', '40,000 kms', '11,400 kms',
       '97,200 kms', '52,000 kms', '31,000 kms', '1,75,430 kms',
       '37,000 kms', '65,000 kms', '3,350 kms', '75,000 kms',
       '62,000 kms', '73,000 kms', '2,200 kms', '54,870 kms',
       '34,580 kms', '97,000 kms', '60 kms', '80,200 kms', '3,200 kms',
       '0,000 kms', '5,000 kms', '588 kms', '71,200 kms', '1,75,400 kms',
       '9,300 kms', '56,758 kms', '10,000 kms', '56,450 kms',
       '56,000 kms', '32,700 kms', '9,000 kms', '73 kms', '1,60,000 kms',
       '58,559 kms', '57,000 kms', '1,70,000 kms', '80,000 kms',
       '6,821 kms', '23,000 kms', '34,000 kms', '1,800 kms',
       '4,00,000 kms', '48,000 kms', '90,000 kms', '12,000 kms',
       '69,900 kms', '1,66,000 kms', '122 kms', '0 kms', '36,469 kms',
       '7,800 kms', '24,695 kms', '15,141 kms', '59,910 kms',
       '1,00,000 kms', '4,500 kms', '1,29,000 kms', '300 kms',
       '1,31,000 kms', '1,11,111 kms', '59,466 kms', '25,500 kms',
       '44,005 kms', '2,110 kms', '43,222 kms', '1,00,200 kms', '65 kms',
       '1,40,000 kms', '1,03,553 kms', '58,000 kms', '1,20,000 kms',
       '49,800 kms', '100 kms', '81,876 kms', '6,020 kms', '55,700 kms',
       '18,500 kms', '53,000 kms', '35,500 kms', '22,134 kms',
       '1,000 kms', '8,500 kms', '87,000 kms', '6,000 kms', '8,000 kms',
       '55,800 kms', '56,400 kms', '72,160 kms', '11,500 kms',
       '1,33,000 kms', '2,000 kms', '88,000 kms', '65,422 kms',
       '1,17,000 kms', '1,50,000 kms', '10,750 kms', '6,800 kms',
       '9,800 kms', '57,923 kms', '30,201 kms', '6,200 kms', '37,518 kms',
       '24,652 kms', '383 kms', '95,000 kms', '3,528 kms', '52,500 kms',
       '47,900 kms', '52,800 kms', '1,95,000 kms', '48,008 kms',
       '48,247 kms', '9,400 kms', '64,000 kms', '2,137 kms', '10,544 kms',
       '1,47,000 kms', '90,001 kms', '48,006 kms', '74,000 kms',
       '85,000 kms', '29,500 kms', '39,700 kms', '67,000 kms',
       '19,336 kms', '60,105 kms', '45,933 kms', '1,02,563 kms',
       '28,600 kms', '41,800 kms', '1,16,000 kms', '42,590 kms',
       '7,400 kms', '54,500 kms', '76,000 kms', '00 kms', '11,523 kms',
       '38,600 kms', '95,500 kms', '37,458 kms', '85,960 kms',
       '12,516 kms', '30,600 kms', '2,550 kms', '62,500 kms',
       '69,000 kms', '28,400 kms', '68,485 kms', '3,500 kms',
       '85,455 kms', '63,000 kms', '1,600 kms', '77,000 kms',
       '26,500 kms', '2,875 kms', '13,900 kms', '1,500 kms', '2,450 kms',
       '1,625 kms', '33,400 kms', '60,123 kms', '1,37,495 kms',
       '91,200 kms', '1,46,000 kms', '1,00,800 kms', '2,100 kms',
       '2,500 kms', '1,32,000 kms', 'Petrol'], dtype=object)

In [15]:
car['kms_driven'] = car['kms_driven'].str.split(' ').str.get(0).str.replace(',','')

In [16]:
car['kms_driven'].unique()

array(['45000', '40', '28000', '36000', '41000', '25000', '24530',
       '60000', '30000', '32000', '48660', '4000', '16934', '43000',
       '35550', '39522', '39000', '55000', '72000', '15975', '70000',
       '23452', '35522', '48508', '15487', '82000', '20000', '68000',
       '38000', '27000', '33000', '46000', '16000', '47000', '35000',
       '30874', '15000', '29685', '130000', '19000', '54000', '13000',
       '38200', '22000', '50000', '13500', '3600', '45863', '60500',
       '12500', '18000', '13349', '29000', '44000', '42000', '14000',
       '49000', '36200', '51000', '104000', '33333', '33600', '5600',
       '7500', '26000', '24330', '65480', '200000', '59000', '99000',
       '2800', '21000', '11000', '66000', '3000', '7000', '38500',
       '37200', '43200', '24800', '45872', '40000', '11400', '97200',
       '52000', '31000', '175430', '37000', '65000', '3350', '75000',
       '62000', '73000', '2200', '54870', '34580', '97000', '60', '80200',
       '3200', '0000', '5000', '588', '71200', '175400', '9300', '56758',
       '10000', '56450', '56000', '32700', '9000', '73', '160000',
       '58559', '57000', '170000', '80000', '6821', '23000', '34000',
       '1800', '400000', '48000', '90000', '12000', '69900', '166000',
       '122', '0', '36469', '7800', '24695', '15141', '59910', '100000',
       '4500', '129000', '300', '131000', '111111', '59466', '25500',
       '44005', '2110', '43222', '100200', '65', '140000', '103553',
       '58000', '120000', '49800', '100', '81876', '6020', '55700',
       '18500', '53000', '35500', '22134', '1000', '8500', '87000',
       '6000', '8000', '55800', '56400', '72160', '11500', '133000',
       '2000', '88000', '65422', '117000', '150000', '10750', '6800',
       '9800', '57923', '30201', '6200', '37518', '24652', '383', '95000',
       '3528', '52500', '47900', '52800', '195000', '48008', '48247',
       '9400', '64000', '2137', '10544', '147000', '90001', '48006',
       '74000', '85000', '29500', '39700', '67000', '19336', '60105',
       '45933', '102563', '28600', '41800', '116000', '42590', '7400',
       '54500', '76000', '00', '11523', '38600', '95500', '37458',
       '85960', '12516', '30600', '2550', '62500', '69000', '28400',
       '68485', '3500', '85455', '63000', '1600', '77000', '26500',
       '2875', '13900', '1500', '2450', '1625', '33400', '60123',
       '137495', '91200', '146000', '100800', '2100', '2500', '132000',
       'Petrol'], dtype=object)

In [17]:
car = car[car['kms_driven'].str.isnumeric()]

In [18]:
car['kms_driven'] = car['kms_driven'].astype(int)

In [19]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 817 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        817 non-null    object
 1   company     817 non-null    object
 2   year        817 non-null    int64
 3   Price       817 non-null    int64
 4   kms_driven  817 non-null    int64
 5   fuel_type   816 non-null    object
dtypes: int64(3), object(3)
memory usage: 44.7+ KB

In [20]:
car['fuel_type'].unique()

array(['Petrol', 'Diesel', nan, 'LPG'], dtype=object)

In [21]:
car['fuel_type'].isna()

0      False
1      False
3      False
4      False
6      False
       ...
883    False
885    False
886    False
888    False
889    False
Name: fuel_type, Length: 817, dtype: bool

In [23]:
#car[~car['fuel_type'].isna()]

In [24]:
car = car[~car['fuel_type'].isna()]

In [25]:
car['name'].str.split(' ')

0        [Hyundai, Santro, Xing, XO, eRLX, Euro, III]
1                        [Mahindra, Jeep, CL550, MDI]
3      [Hyundai, Grand, i10, Magna, 1.2, Kappa, VTVT]
4              [Ford, EcoSport, Titanium, 1.5L, TDCi]
6                                        [Ford, Figo]
                            ...
883                  [Maruti, Suzuki, Ritz, VXI, ABS]
885                  [Tata, Indica, V2, DLE, BS, III]
886                          [Toyota, Corolla, Altis]
888                          [Tata, Zest, XM, Diesel]
889                            [Mahindra, Quanto, C8]
Name: name, Length: 816, dtype: object

In [26]:
car['name'].str.split(' ').str.slice(0,3)

0         [Hyundai, Santro, Xing]
1         [Mahindra, Jeep, CL550]
3           [Hyundai, Grand, i10]
4      [Ford, EcoSport, Titanium]
6                    [Ford, Figo]
                  ...
883        [Maruti, Suzuki, Ritz]
885            [Tata, Indica, V2]
886      [Toyota, Corolla, Altis]
888              [Tata, Zest, XM]
889        [Mahindra, Quanto, C8]
Name: name, Length: 816, dtype: object

In [28]:
car['name'] = car['name'].str.split(' ').str.slice(0,3).str.join(' ')

In [29]:
car

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
3         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
4    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
6                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
883      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
885          Tata Indica V2      Tata  2009  110000       30000    Diesel
886    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
888            Tata Zest XM      Tata  2018  260000       27000    Diesel
889      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[816 rows x 6 columns]

In [31]:
car = car.reset_index(drop = True)

In [33]:
car.head()

                     name   company  year   Price  kms_driven fuel_type
0     Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1     Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2       Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3  Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4               Ford Figo      Ford  2012  175000       41000    Diesel

In [34]:
car.describe()

              year         Price     kms_driven
count   816.000000  8.160000e+02     816.000000
mean   2012.444853  4.117176e+05   46275.531863
std       4.002992  4.751844e+05   34297.428044
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.912500e+05   56818.500000
max    2019.000000  8.500003e+06  400000.000000

In [35]:
car[car['Price']>6e6]

                   name   company  year    Price  kms_driven fuel_type
534  Mahindra XUV500 W6  Mahindra  2014  8500003       45000    Diesel

In [37]:
car[car['Price']>3e6]

                   name   company  year    Price  kms_driven fuel_type
534  Mahindra XUV500 W6  Mahindra  2014  8500003       45000    Diesel
678   Audi A3 Cabriolet      Audi  2015  3100000       12516    Petrol

In [38]:
car = car[car['Price']<6e6].reset_index(drop = True)

In [39]:
car

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
811          Tata Indica V2      Tata  2009  110000       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
813            Tata Zest XM      Tata  2018  260000       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[815 rows x 6 columns]

In [40]:
car.to_csv('Quikr Car Data.csv')

**Modelling**

In [41]:
X = car.drop(columns = 'Price')
y = car['Price']

In [42]:
X

                       name   company  year  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006          40    Diesel
2         Hyundai Grand i10   Hyundai  2014       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014       36000    Diesel
4                 Ford Figo      Ford  2012       41000    Diesel
..                      ...       ...   ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011       50000    Petrol
811          Tata Indica V2      Tata  2009       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009      132000    Petrol
813            Tata Zest XM      Tata  2018       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013       40000    Diesel

[815 rows x 5 columns]

In [43]:
y

0       80000
1      425000
2      325000
3      575000
4      175000
        ...
810    270000
811    110000
812    300000
813    260000
814    390000
Name: Price, Length: 815, dtype: int64

In [44]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder

In [45]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [46]:
ohe = OneHotEncoder()
ohe.fit(X[['name', 'company', 'fuel_type']])

OneHotEncoder()

In [47]:
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [49]:
column_trans = make_column_transformer((OneHotEncoder(categories= ohe.categories_), ['name', 'company', 'fuel_type']), remainder = 'passthrough')

In [50]:
lr = LinearRegression()

In [51]:
pipe = make_pipeline(column_trans, lr)

In [52]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [53]:
y_pred = pipe.predict(X_test)

In [54]:
y_pred

array([ 4.56073460e+05,  1.39815585e+04,  7.16576481e+05,  6.95044740e+05,
       -8.76923727e+04,  5.02820761e+04,  9.29192308e+04,  4.08181677e+05,
        2.04994046e+05,  3.95507354e+05,  3.90002748e+05,  7.77586013e+05,
        5.85968767e+05,  9.00498774e+04,  5.91761275e+05,  2.81436105e+05,
        1.81798609e+05,  1.13596758e+05,  1.28172110e+06,  4.24343145e+05,
        2.25156591e+05,  9.56099175e+04,  4.21929881e+05,  1.74205229e+05,
        4.50846062e+05,  2.12262778e+05,  4.56026759e+05,  4.50846062e+05,
       -4.44265267e+04, -6.94811190e+04,  3.07137846e+05, -1.83057593e+05,
        6.10436814e+05,  3.67272946e+05,  1.86427961e+05,  7.73846722e+04,
        2.98756510e+05,  1.90526306e+05,  3.32171245e+05,  5.98841223e+05,
        2.71964640e+05,  3.29382553e+05,  1.25914153e+05,  1.32488075e+05,
        1.29304083e+05,  3.44603079e+05,  3.74278927e+05,  6.95428463e+05,
        9.19882059e+04,  4.07887616e+05,  4.95473287e+05,  1.47100555e+06,
        5.59999258e+04,  3.34411983e+02,  2.22951672e+06,  2.67491565e+05,
        2.23027731e+05,  3.26646290e+05,  1.97219382e+05,  5.70968656e+05,
        2.45959088e+05,  1.61446160e+05,  6.06899447e+05,  2.34329117e+05,
        1.73751114e+06,  5.38335571e+05,  3.02181903e+05,  2.28514132e+05,
        4.39735227e+05,  5.68664268e+05,  6.72086649e+05,  5.23390290e+05,
        4.28759725e+05,  2.26403236e+05,  6.07591231e+05,  1.88204415e+05,
        4.27265336e+05,  9.16007894e+05,  6.89459405e+05,  4.02329123e+05,
        5.16290048e+05,  1.88204415e+05,  3.22430033e+05,  2.54596805e+05,
        2.49397677e+05,  2.43372370e+05,  3.05279468e+05,  7.05603430e+05,
        6.21419674e+05,  1.59326618e+06,  1.96895827e+05,  4.37988362e+05,
        6.23887319e+05,  2.91776012e+05,  4.36941812e+05,  3.07233488e+05,
        2.52318439e+05,  3.26367643e+05,  3.66104056e+05, -1.30753125e+05,
        5.26512855e+05,  1.55549967e+04,  3.71163523e+05,  3.71294978e+05,
        2.43663119e+05,  2.92768860e+05,  4.90794922e+05,  2.52403901e+05,
        3.15236342e+05,  4.28401972e+05,  5.17158218e+05,  1.15039871e+05,
        8.08229012e+05,  3.49931094e+05,  3.70135780e+05,  2.30097005e+05,
        4.57244117e+05,  2.50320327e+05,  4.36482561e+05,  4.17490940e+05,
        6.07591231e+05,  1.65064694e+05,  4.31141993e+05,  1.06963872e+06,
        5.19011819e+05,  2.47340657e+05,  2.64114288e+05,  3.38589613e+05,
        2.74290512e+05,  5.97300842e+05,  2.10089378e+05,  9.60944996e+04,
        4.97523085e+05,  8.16642750e+05,  2.65742051e+05,  4.49392316e+05,
        4.34293082e+05,  1.90122473e+05,  2.48888910e+05,  9.40106761e+05,
       -3.80974763e+04,  6.95428463e+05,  3.20447160e+05,  1.07053246e+06,
        6.46302706e+04,  6.79788671e+05,  4.97523085e+05,  4.48438205e+05,
        4.27436414e+05,  3.57882293e+05,  5.86959719e+05,  5.70988885e+05,
        5.98178409e+05,  4.26296172e+05,  6.35820680e+05,  1.51950882e+05,
        6.30784389e+05,  1.16588050e+05,  5.76398502e+03,  6.34024145e+05,
        2.39630078e+05,  3.32600969e+04,  1.58086945e+04])

In [55]:
r2_score(y_test, y_pred)

0.5888484807036288

Finding the model with a random state of TrainTestSplit where the model will give the most of as r2_score

In [56]:
import numpy as np

In [57]:
scores=[]
for i in range(1000):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=i)
    lr=LinearRegression()
    pipe=make_pipeline(column_trans,lr)
    pipe.fit(X_train,y_train)
    y_pred=pipe.predict(X_test)
    scores.append(r2_score(y_test,y_pred))

In [58]:
np.argmax(scores)

302

In [59]:
scores[np.argmax(scores)]

0.8991190499074018

In [60]:
pipe.predict(pd.DataFrame(columns=X_test.columns,data=np.array(['Maruti Suzuki Swift','Maruti',2019,100,'Petrol']).reshape(1,5)))

array([430382.81414542])

In [61]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=np.argmax(scores))
lr=LinearRegression()
pipe=make_pipeline(column_trans,lr)
pipe.fit(X_train,y_train)
y_pred=pipe.predict(X_test)
r2_score(y_test,y_pred)

0.8991190499074018

In [62]:
import pickle

In [63]:
pickle.dump(pipe,open('LinearRegressionModel.pkl', 'wb'))